### ISSUE TITLE
音色の実装の希望

### ISSUE THREAD

**Issue by Donkama765** [Mr-Ojii/TJAPlayer3-f#1]
まあ希望としては、選曲画面を本家風にしてほしいです。難易度選択かな？

**Comment by Mr-Ojii** [comment]
間違えて、Closeを押してしまいました。すみません。
要望を確認いたしました。
お伺いしたいのですが、選曲画面の本家風というのは、
曲選択後に難易度選択画面を表示するという解釈でよろしいでしょうか？

**Comment by elizanan44** [comment]
本人じゃなくてすみません。こんな感じのものだと思いますhttps://youtu.be/pRclzqoOhEM

**Comment by Mr-Ojii** [comment]
長期間返信がないため、このIssueはCloseさせていただきます。
もし、このIssueについて言及するのでしたら、お手数ですがReOpenしてください。

**Comment by RinMC1593** [comment]
音色とかですね。出来れば追加も簡単に出来るようにして欲しいです

**Comment by Donkama765** [comment]
間違えたぜ

**Comment by Mr-Ojii** [comment]
音色機能を実装いたしました。

Sounds\Taikoフォルダの中に連番のフォルダを作り、
そのフォルダ内に「dong.ogg」「ka.ogg」「Adlib.ogg」を入れ、
Sounds\Taiko\SElist.csvに行を追加し、その音色の説明を記載することで追加が可能となります。
(一応、csvの記述方法にのっとり、カンマ区切りでも可)


### 注意点
* フォルダだけ作り、フォルダ内に音声ファイルが存在しない場合でも、1音色としてカウントされます。
* ファイルが欠けている場合、Sounds\Taiko内の音声を使用します。
* SElist.csvの行が足りない場合、「無名」という説明になります。
* 連番フォルダが全くない状態では、「音色をかえる」フェーズは無効化されます。

**Comment by Mr-Ojii** [comment]
長期間返信がないため、このIssueはCloseさせていただきます。
