### ISSUE TITLE
選曲画面の音源プレビュー

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#11]
TJAP3-ｆはプレビュー終了後に最初から音源が再生されるACはDEMOSTARTで指定したところから再度再生される

**Comment by Mr-Ojii** [comment]
使用しているライブラリの仕様なのでできるかどうかはわかりませんが、
できる限りのことは試してみます。

**Comment by Mr-Ojii** [comment]
ライブラリの仕様だと思ったのですが、違いました。
実装します。
