### ISSUE TITLE
選曲画面での曲読み込み時に読み込んだTJAの文字列によってScrollModeが勝手に切り替わるのを修正

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#12]
勝手に切り替わるのを修正してほしいです。
参考に
http://github.com/rhimm/TJAPlayer3/commit/0d66835fec4e55b3c4c6d2e524c04e8cccee55de

**Comment by Mr-Ojii** [comment]
修正いたします。
参考資料ありがとうございます。
