### ISSUE TITLE
譜面内にLYRIC命令やlrcファイルがある譜面には歌詞付という画像を表示する

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#13]
LYRIC命令やlrcファイルがある譜面には歌詞付という画像を表示してほしいです。
ジャンルごとに色分けをしてほしいです。ジャンル分けがない譜面は白のままで
https://youtu.be/ZE15ZwBt118

**Comment by Mr-Ojii** [comment]
今のところ、譜面分岐表示の画像と重なってしまうのと、lrcファイルの対応がまだなので
譜面分岐の画像位置の変更とlrcファイルの対応をしてから、実装いたします。

**Comment by ghost** [comment]
歌詞付の画像をSkinConfig.iniで変更できるようにできませんか？

**Comment by Mr-Ojii** [comment]
歌詞付の画像をSkinConfig.iniで変更できるようにするメリットがわかりません。
画像を差し替えるだけではだめなのでしょうか？
メリットがある場合、教えてもらいたいです。
よろしくおねがいします。

**Comment by ghost** [comment]
すみません。画像を差し替えるようにします。

**Comment by Mr-Ojii** [comment]
承知いたしました。
このIssueはCloseしても大丈夫でしょうか？

**Comment by ghost** [comment]
分かりました。お騒がせしてすみませんでした。

**Comment by Mr-Ojii** [comment]
いえいえ、大丈夫ですよ。
では、このIssueはCloseさせていただきます。
