### ISSUE TITLE
#SUDDEN を記述した時の符の出現タイミングがおかしい

### ISSUE THREAD

**Issue by Sinno0105** [Mr-Ojii/TJAPlayer3-f#17]
**Describe the bug**
#SUDDEN 命令がおかしい

**To Reproduce**
1. #SUDDEN イベントを記述したtjaファイルを遊ぶ

**Expected behavior**
#SUDDEN 命令を記述したにも関わらず
符が最初から表示されている

**Screenshots**
![20200513214452](https://user-images.githubusercontent.com/65291872/81815548-141e7f80-9565-11ea-8aad-4e5940464011.png)

**Desktop (please complete the following information):**
Windows 8

**Additional context**
大まかに言うと#SUDDEN命令を書いたときの符の出現タイミングがおかしいということです。
動き出すタイミングは正常でした。（語彙力無くてすいません）

**Comment by Mr-Ojii** [comment]
こちらの環境でもバグが確認できましたので、修正いたします。

**Comment by Sinno0105** [comment]
修正が確認できました！
ありがとうございます！
