### ISSUE TITLE
ビルドすると謎のエラーが出る

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#20]
ビルドすると謎のエラーが出るのですが原因分かりますか？move /y "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\FDK.dll" "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\dll\"
move /y "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\FDK.pdb" "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\dll\"
move /y "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\Bass.Net.dll" "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\dll\"
move /y "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\DirectShowLib-2005.dll" "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\dll\"
move /y "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\SlimDX.dll" "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\dll\"
move /y "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\CSharpTest.Net.Collections.*" "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\dll\"
move /y "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\SharpDX*.dll" "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\dll\"
del "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\SharpDX*.xml"
del "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\SharpDX*.pdb"
copy /y "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Readme.txt" "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\"
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\..\Tools\VsDevCmd.bat"
"editbin.exe" /LARGEADDRESSAWARE "C:\Users\(ユーザー名)\Desktop\TJAPlayer3-f-master\Test\TJAPlayer3-f.exe"" はコード 9009 で終了しました。	TJAPlayer3-f

**Comment by Mr-Ojii** [comment]
すみません。こちらの環境では、エラーが再現できないので、
詳しくはわかりかねますが、できる限りの対策をしてみます。

**Comment by Mr-Ojii** [comment]
自分がわかる限りの対策を致したのですが、直っておりますでしょうか？

**Comment by ghost** [comment]
直っていませんでした

**Comment by Mr-Ojii** [comment]
新たな変更を加えたのですが、どうでしょうか？

**Comment by ghost** [comment]
直りましたありがとうございました。　結局エラーの原因は何ですか？

**Comment by Mr-Ojii** [comment]
この文字列は、TJAP3fのビルド後に行う作業の一覧なのですが、
エラーコードの最後の方に書いてある"editbin.exe"がフルパス参照ではないので、
動作しなかったために、起こるエラーのようです。
「VS 9009エラー」で検索したら、エラー解決法がたくさん出てきました。

**Comment by ghost** [comment]
分かりました。ありがとうございます。

**Comment by Mr-Ojii** [comment]
お役に立てて、何よりです。
では、このIssueはCloseさせていただきます。
