### ISSUE TITLE
難易度Danを選択した後に この段位に挑戦するカッ？の表示

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#21]
難易度Danを選択した後に この段位に挑戦するカッ？の表示を表示してほしいのですができませんか？

**Comment by Mr-Ojii** [comment]
私も実装したいなと思っていました。
実装します。

**Comment by ghost** [comment]
すみません Dan_Select.ogg をSoundEffectに変更できませんでしょうか？

**Comment by Mr-Ojii** [comment]
承知しました。
変更しますね。

**Comment by Mr-Ojii** [comment]
Issue閉じるのを忘れていました。
実装しましたので、閉じさせていただきます。
