### ISSUE TITLE
譜面分岐のバグ

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#22]
るてしキスキしてる【さかさまのさかさまモード】の裏譜面で終盤当たりで譜面が途中ぐちゃぐちゃになって途中で演奏終了になってしまいました。次郎で見比べてみると分岐も結構しているのですがTJAP3-fでは分岐されませんでした。BRANCHSTARTのマイナスは対応しているのでしょうか？http://ux.getuploader.com/LoveLive_Jiro/download/79

**Comment by Mr-Ojii** [comment]
BRANCHSTARTのマイナスは対応しています。

玄人譜面への強制分岐が
#BRANCHSTARTp,0,101
と指定されているのが原因かもしれません。(玄人譜面への強制分岐はp,-1,101と表記してほしいです)

しかしながら、太鼓さん次郎のほうでは、分岐がうまくいっている様ですので、精度分岐を判定する式が間違っている様です。早急に修正いたします。

**Comment by ghost** [comment]
分岐はされましたが最後の方が次郎と見比べてみると分岐されていてTJAP3は分岐されていませんでした。後リザルト画面に行きません。

**Comment by Mr-Ojii** [comment]
リザルト画面に行かない理由がわかりました。
該当tjaファイルの691行目の#BRANCHSTARTの最後の部分に不必要な「,」が入力されているためのようです。

現在、正規表現で分割しているため、「#BRANCHSTART?,X,Y」の形に一致しないと、エラーを起こして、tjaの解析が途中で止まってしまうようです。(正規表現についてよくわかっていないので説明が間違っているかもしれませんが。)

別の方法で分割するなどをして、対処します。

**Comment by ghost** [comment]
修正が確認できました。ありがとうございます。
