### ISSUE TITLE
一部の曲のスコアは保存されるが画像が表示されない

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#24]
まだ一曲しか確認できていませんがスコアは保存されるが画像が表示されません

**Comment by Mr-Ojii** [comment]
何の画像が表示されないのでしょうか？

**Comment by ghost** [comment]
王冠の画像が表示しません

**Comment by Mr-Ojii** [comment]
どの画面で王冠画像が表示されないのでしょうか？
選曲画面でしょうか？
結果発表画面でしょうか？

選曲画面である場合、Bar_Centerに重なっている王冠でしょうか？
それとも、Bar_Genreに重なっている王冠でしょうか？

**Comment by ghost** [comment]
選曲画面、Bar_Center、Bar_Genreです。一応譜面置いておきます。http://ux.getuploader.com/LoveLive_NSD_Jiro/download/38

**Comment by Mr-Ojii** [comment]
ありがとうございます。
確認してみます。

**Comment by Mr-Ojii** [comment]
すみません。score.iniを削除したりして、何度も試してみたのですが、
王冠が表示されないバグは、こちらの環境では再現できませんでした。

こちらの環境でも、同様のバグが確認され次第、直しますが、
一応、今日か明日に、Ver.1.6.0.0をコミットするので、
少々お待ちいただたいて、そちらでも、試してみてもらえますでしょうか。

Ver.1.6.0.0 開発段階のスクリーンショット
![image](https://user-images.githubusercontent.com/59733587/83633836-87ebff00-a5dc-11ea-950e-f626deb40c9b.png)

**Comment by ghost** [comment]
scoreiniのデータを消したら直りました。ありがとうございました。

**Comment by Mr-Ojii** [comment]
それはよかったです。
では、このIssueはClose致しますね。
