### ISSUE TITLE
特訓モード実装

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#26]
演奏中にQキーを押すと一時停止、PageUp 右ふちで次に行くPageDown左ふちで前に戻る、Spaceで再生 再生するときに少し前に戻ってフェードインしてから再開　再生中のゲージも実装してほしいです。再生速度を下げると音源を再生しないようにする
https://youtu.be/_nyDmP_sMSA

**Comment by Mr-Ojii** [comment]
特訓モードをテスト実装しましたので、お試しください。
**操作方法などが提示されたものと多少異なっています。**

Spaceキーで再生/停止
←/PgUp/左ふちで前の小節に移動
→/PgDn/右ふちで次の小節に移動
2Pの右ふち左ふちで再生速度の変更

再生するときに少し前に戻るが、フェードインしないで再開
再生中のゲージも実装
再生速度を変更しても音源は再生されます

**Comment by ghost** [comment]
質問です。終了のところは#ENDのところまででしょうか？可能であれば音源の終了まで再生は可能でしょうか？途中で途切れてしまう曲もありますので。　あと魂ゲージが表示されない問題もあります。PgUp/PgDnおしても移動できません。後特訓モード選択中に段位譜面を選択できないようにしてほしいです。

**Comment by Mr-Ojii** [comment]
終了は今のところ#ENDまでです。
音源の終了まで再生を試みてみます。

魂ゲージが表示されないのは仕様です。

PgUp/PgDnおしても移動できないことについては私のコミット漏れです。
申し訳ございません。
追加いたします。

特訓モード選択中に段位譜面を選択できないように修正いたします。

**Comment by ghost** [comment]
修正ありがとうございます。追加で申し訳ないです。ジャンプポイントを追加してほしいです。何回も練習したい所に戻るのが大変なので 5回ふちを押すと登録した部分にジャンプする仕組みです。演奏中にオートがON OFFできるようにしてほしいです。後再生中のゲージが枠からはみ出てしまいます。オート中に一時停止して移動すると譜面が反応してしまいます。
