### ISSUE TITLE
王冠機能の実装

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#3]
王冠機能の実装できますか？

**Comment by Mr-Ojii** [comment]
実装に数日はかかると思いますが、多分、できると思います。
選曲画面のところに王冠が表示されればいいのですかね？

**Comment by ghost** [comment]
はい。後scoreiniにデータを残してくれるようにしてもらえると嬉しいです。

**Comment by Mr-Ojii** [comment]
承知いたしました。
では、score.iniにCrownというアイテム名でデータを残すようにしたいと思います。

実装、頑張りますね。

**Comment by ghost** [comment]
追加で申し訳ないのですがリザルト画面にも王冠の画像を表示させてほしいです。

**Comment by Mr-Ojii** [comment]
承知しました。

**Comment by Mr-Ojii** [comment]
リザルト画面にも王冠の画像を表示させるようにしたはずですが、どうでしょうか？

**Comment by ghost** [comment]
大丈夫そうです。後、SkinConfig.iniで画像の位置をだれでも変更できるようにして欲しです。何回も申し訳ないです

**Comment by Mr-Ojii** [comment]
いえいえ、要望を言ってもらえることはとてもうれしいことですから、謝らなくてもいいですよ。
私も、皆さんが使いやすいと思えるようなものにしていきたいですし。

SkinConfig.iniで王冠の画像の位置を変更できるようにする設定は、次の更新で適用したいと思います。

**Comment by ghost** [comment]
ほかの難易度を選択すると鬼の画像が消えてしまうのでそれの修正してほしいです。

**Comment by Mr-Ojii** [comment]
すみません。
「ほかの難易度を選択すると鬼の画像が消えてしまう」というのは
どういうことでしょうか。

もうちょっと詳しい説明をお願いします。

**Comment by ghost** [comment]
こちらの動画を見てもらえればわかるかと思います。
[bandicam 2020-04-15 22-16-52-655.zip](https://github.com/Mr-Ojii/TJAPlayer3-f/files/4481373/bandicam.2020-04-15.22-16-52-655.zip)

**Comment by Mr-Ojii** [comment]
CS風に現在選択中の難易度の各曲ごとの王冠を表示するという風にしているので、このようなことが起こります。
つまり、今のところこういう仕様なのですが、AC風の王冠の表示方法も実装しましょうか？
あなたが、望むのであれば、僕も喜んで実装いたしますが。

**Comment by ghost** [comment]
是非お願いします

**Comment by Mr-Ojii** [comment]
承知しました。
Config.iniで王冠の表示方法をCS風かAC風か設定できるようにしたいとおもいます。

**Comment by Mr-Ojii** [comment]
AC風の王冠表示方法を実装しました。
もし、今までと変わっていないのならば、
コンフィグから、CrownDispACをONにしてください。

**Comment by ghost** [comment]
一部の曲が保存されていないようです。一時期王冠は出ますかデータを再取得すると消えます。

**Comment by Mr-Ojii** [comment]
[このリンク](https://github.com/Mr-Ojii/TJAPlayer3-f/issues/4)のIssueと同一ですね。
その他の問題がないのであれば、[こちら](https://github.com/Mr-Ojii/TJAPlayer3-f/issues/4)のIssueに移行します。

**Comment by ghost** [comment]
CrownDispACをONにしても消えます

**Comment by Mr-Ojii** [comment]
承知しております。その問題を含んでのIssueの移行をいたします。

[こちら](https://github.com/Mr-Ojii/TJAPlayer3-f/issues/4)のIssueに移行
