### ISSUE TITLE
ソフト起動時にエラーが発生する

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#33]
エラー文(TJAPlayer3-fから開いた場合は自動入力されます)
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 TJAPlayer3.CActSelect曲リスト.OnManagedリソースの作成() 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\TJAPlayer3\Stages\05.SongSelect\CActSelect曲リスト.cs:行 609
   場所 FDK.CActivity.On活性化() 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\FDK19\コード\00.共通\CActivity.cs:行 56
   場所 TJAPlayer3.CActSelect曲リスト.On活性化() 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\TJAPlayer3\Stages\05.SongSelect\CActSelect曲リスト.cs:行 577
   場所 TJAPlayer3.CActSelect曲リスト.Refresh(CSongs管理 cs, Boolean bRemakeSongTitleBar) 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\TJAPlayer3\Stages\05.SongSelect\CActSelect曲リスト.cs:行 472
   場所 TJAPlayer3.CStage選曲.Refresh(CSongs管理 cs, Boolean bRemakeSongTitleBar) 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\TJAPlayer3\Stages\05.SongSelect\CStage選曲.cs:行 159
   場所 TJAPlayer3.TJAPlayer3.Draw(GameTime gameTime) 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\TJAPlayer3\Common\TJAPlayer3.cs:行 738
   場所 SampleFramework.Game.DrawFrame() 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\FDK19\コード\01.フレームワーク\Core\Game.cs:行 510
   場所 SampleFramework.Game.Tick() 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\FDK19\コード\01.フレームワーク\Core\Game.cs:行 376
   場所 SampleFramework.Game.Application_Idle(Object sender, EventArgs e) 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\FDK19\コード\01.フレームワーク\Core\Game.cs:行 531
   場所 System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   場所 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   場所 System.Windows.Forms.Application.Run(Form mainForm)
   場所 SampleFramework.Game.Run() 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\FDK19\コード\01.フレームワーク\Core\Game.cs:行 261
   場所 TJAPlayer3.Program.Main() 場所 C:\Users\TSUYOSHI\Desktop\TJAPlayer3-f-master\TJAPlayer3\Common\Program.cs:行 135

使用しているスキン名・バージョン
1.6.0 Honkehuu

バグを引き起こすまでの手順を書いてください
ソフト起動時にエラーが発生しました。

再生していた譜面(.tja)または画面
-
使用しているOS
Windows10 64bit 1909

不具合の内容
ソフト起動時にエラーが発生しました。

(追加情報を自由に書いてください(任意))

**Comment by ghost** [comment]
修正ありがとうございます

**Comment by Rinku8** [comment]
オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 TJAPlayer3.CActSelect難易度選択画面.On進行描画() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\TJAPlayer3\Stages\05.SongSelect\CActSelect難易度選択画面.cs:行 317
   場所 TJAPlayer3.CStage選曲.On進行描画() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\TJAPlayer3\Stages\05.SongSelect\CStage選曲.cs:行 710
   場所 TJAPlayer3.TJAPlayer3.Draw(GameTime gameTime) 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\TJAPlayer3\Common\TJAPlayer3.cs:行 675
   場所 SampleFramework.Game.DrawFrame() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\FDK19\コード\01.フレームワーク\Core\Game.cs:行 511
   場所 SampleFramework.Game.Tick() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\FDK19\コード\01.フレームワーク\Core\Game.cs:行 377
   場所 SampleFramework.Game.Application_Idle(Object sender, EventArgs e) 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\FDK19\コード\01.フレームワーク\Core\Game.cs:行 532
   場所 System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   場所 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   場所 System.Windows.Forms.Application.Run(Form mainForm)
   場所 SampleFramework.Game.Run() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\FDK19\コード\01.フレームワーク\Core\Game.cs:行 262
   場所 TJAPlayer3.Program.Main() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\TJAPlayer3\Common\Program.cs:行 144
エラーだゴメン！（涙

**Comment by Rinku8** [comment]
オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 TJAPlayer3.CActSelect難易度選択画面.On進行描画() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\TJAPlayer3\Stages\05.SongSelect\CActSelect難易度選択画面.cs:行 317
   場所 TJAPlayer3.CStage選曲.On進行描画() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\TJAPlayer3\Stages\05.SongSelect\CStage選曲.cs:行 710
   場所 TJAPlayer3.TJAPlayer3.Draw(GameTime gameTime) 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\TJAPlayer3\Common\TJAPlayer3.cs:行 675
   場所 SampleFramework.Game.DrawFrame() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\FDK19\コード\01.フレームワーク\Core\Game.cs:行 511
   場所 SampleFramework.Game.Tick() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\FDK19\コード\01.フレームワーク\Core\Game.cs:行 377
   場所 SampleFramework.Game.Application_Idle(Object sender, EventArgs e) 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\FDK19\コード\01.フレームワーク\Core\Game.cs:行 532
   場所 System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   場所 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   場所 System.Windows.Forms.Application.Run(Form mainForm)
   場所 SampleFramework.Game.Run() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\FDK19\コード\01.フレームワーク\Core\Game.cs:行 262
   場所 TJAPlayer3.Program.Main() 場所 D:\a\TJAPlayer3-Develop-ReWrite\TJAPlayer3-Develop-ReWrite\TJAPlayer3\Common\Program.cs:行 144

使用しているOS
Windows11 Pro 64bit

難易度選択画面に移動した瞬間に、エラーが発生してクラッシュしました
