### ISSUE TITLE
演奏終了後にやり直しを押すとリザルト画面に行く

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#36]
演奏終了後にやり直しを押すとリザルト画面に行って音源がながれっぱなしでやり直しができません。終了後にもやり直せるようにしてほしいです。http://vimeo.com/435082917

**Comment by Mr-Ojii** [comment]
こちらでもバグの再現ができましたので、修正いたします。

**Comment by Mr-Ojii** [comment]
修正いたしました。ご確認ください。

**Comment by ghost** [comment]
修正が確認できました。ありがとうございます。
