### ISSUE TITLE
SoundTypeを変更するとSEやボイスが再生される

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#37]
SoundTypeを変更すると選曲画面等のSEやボイスが再生さます。音量を０にしていても演奏画面は再生されません。

**Comment by Mr-Ojii** [comment]
> SoundTypeを変更すると選曲画面等のSEやボイスが再生さます。
> 音量を０にしていても演奏画面は再生されません。

という言葉の解釈が
「コンフィグ画面でSoundTypeを変更すると音量設定が適用されない」
ということで合っているのであれば、修正いたしました。
ご確認ください。

**Comment by ghost** [comment]
修正が確認できました。ありがとうございます。
