### ISSUE TITLE
Score.iniに記録されていても、選曲画面に表示されない

### ISSUE THREAD

**Issue by Mr-Ojii** [Mr-Ojii/TJAPlayer3-f#4]
**Describe the bug**
かんたん,ふつうを遊んだ後に、score.iniに記録されない。

**To Reproduce**
1.かんたんか、ふつう譜面を遊ぶ

**Expected behavior**
score.iniに記録をするというパラメータをOnにしているにもかかわらず、
かんたん,ふつうを遊んだ後に、score.iniにハイスコアの記録がされない。

**Comment by Mr-Ojii** [comment]
かんたん、ふつう譜面だけでなく、スコアごとにスコアが保存できない難易度が変わる。
実装しようとしている、王冠機能もスコアが保存できない難易度と同じ難易度が保存ができない。

**Comment by Mr-Ojii** [comment]
TJAPlayer2 for PCでも同様のバグが確認できた。

**Comment by Mr-Ojii** [comment]
全体のスコア(難易度かんたん～Editまで)を全部含めての中でのハイスコアかどうかを基準に
記録の更新を行っていたがために、記録されなかった模様。
修正しました。

よく今まで、修正されなかったね。

**Comment by ghost** [comment]
scoreiniには記録されていて王冠も表示されているのですが曲を再読み込みすると何故か王冠の画像が消えます。

**Comment by ghost** [comment]
何曲かプレイしてみましたが問題なく表示されました。ありがとうございます。

**Comment by Mr-Ojii** [comment]
私も困っていたので、解決できてよかったです。
では、このIssueもCloseいたします。
