### ISSUE TITLE
lrcファイル指定で ，(カンマ)があると読み込みしない

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#45]
lrcファイルを読み込む際  ，(カンマ)があると読み込みしません。

**Comment by Mr-Ojii** [comment]
それは、ファイル名に`,`(カンマ)が含まれていると読み込みをしないということでしょうか？

現状#NEXTSONGに対応するために、カンマ区切りで指定をしてもらうという形になっています。
ですので、lrcファイル名にカンマが含まれている場合、そのカンマでも命令の文字列が切り取られてしまい、
`hoge,hohe.lrc`である場合、`hoge`と`hoge.lrc`であると受け取られてしまいます。

ですので、ファイル名に`,`が含まれていても、.tjaのLYRICFILE命令の指定に`\,`と書けば、エスケープするように変更いたします。
(`hoge,hoge.lrc`である場合、`hoge\,hoge.lrc`と.tjaに書き込めば読み込まれるようにいたします。)

**Comment by ghost** [comment]
修正ありがとうございます
