### ISSUE TITLE
設定画面やボイスなどのバグ

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#5]
設定画面でSE等の設定をしても設定画面を抜けると音がでかくなったり、ボイスの音量を０にしてもさぁ始まるドン(SongDecide.ogg)と成績発表～(ResultIn.ogg)のファイルが再生される不具合がありますので修正可能であればお願いします。

**Comment by Mr-Ojii** [comment]
SE等の設定を変更しても設定画面を抜けると変更が適応されていないバグはこちらでも確認ができたので、対処いたします。

ボイスの音量設定(Voice Level)は、コンボボイスの音量設定ですので、
ボイスの音量設定の方から、「さぁ始まるドン」や、「結果発表～」のボイスの音量は変更できないと思われます。
代わりに、SEの音量設定の方で音量を変えられるように改良いたします。

**Comment by Mr-Ojii** [comment]
訂正いたします。
コードを確認したところ、SongDecide.oggもResultIn.oggもVoiceのカテゴリでした。
確認をしないまま、発言をしてしまったため、間違った情報を言ってしまい、申し訳ございませんでした。

Voiceの音量設定で音量を変えられるようにいたします。
