### ISSUE TITLE
譜面分岐がある譜面プレイ時のバグ

### ISSUE THREAD

**Issue by Mr-Ojii** [Mr-Ojii/TJAPlayer3-f#6]
譜面分岐がある譜面をプレイしたとき、
譜面分岐時にノートを叩けなくなる。

**Comment by ghost** [comment]
見にくいかもしれませんが参考になればご覧くださいhttps://youtu.be/qUYBpRWMpr4

**Comment by Mr-Ojii** [comment]
すみません。
ありがとうございます。

私のほうも今日の夕方くらいから、分岐譜面のバグ修正をいたしておりまして、
最終的にはそちらの動画の直し方と違う直し方で、直してしまうかもしれませんが、
参考にさせていただきます。

**Comment by Mr-Ojii** [comment]
お風呂に入ってるときに思い付いたアイデアで、解消しました。
