### ISSUE TITLE
例外が発生し、起動しない

### ISSUE THREAD

**Issue by 25250512** [Mr-Ojii/TJAPlayer3-f#65]
エラー文(TJAPlayer3-fから開いた場合は自動入力されます)
System.IO.FileLoadException: ファイルまたはアセンブリ 'Hnx8.ReadJEnc, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null'、またはその依存関係の 1 つが読み込めませんでした。厳密な名前付きのアセンブリが必要です。 (HRESULT からの例外:0x80131044)
ファイル名 'Hnx8.ReadJEnc, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null' です。'Hnx8.ReadJEnc, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null'
   場所 TJAPlayer3.CJudgeTextEncoding.JudgeFileEncoding(String path)
   場所 TJAPlayer3.CSkin.<tReadSkinConfig>g__LoadSkinConfigFromFile|55_0(String path, String& work)
   場所 TJAPlayer3.CSkin.tReadSkinConfig()
   場所 TJAPlayer3.CSkin.PrepareReloadSkin()
   場所 TJAPlayer3.CSkin..ctor(String _strSkinSubfolderFullName, Boolean _bUseBoxDefSkin)
   場所 TJAPlayer3.TJAPlayer3.t起動処理()
   場所 TJAPlayer3.TJAPlayer3..ctor()
   場所 TJAPlayer3.Program.Main()

使用しているスキン名・バージョン
わかりません

バグを引き起こすまでの手順を書いてください
起動できない

再生していた譜面(.tja)または画面

使用しているOS
Windows１０

不具合の内容

(追加情報を自由に書いてください(任意))
こんな今更申し訳ないです、。。。
できれば教えてください！

**Comment by Mr-Ojii** [comment]
ご自身でビルドされた場合は、NuGetパッケージの欠落の可能性がございますので、NuGetパッケージの復元後、リビルドをしてください。
Actionsからダウンロードした場合は、ダウンロード時のファイル欠落の可能性がございますので、再ダウンロードを試してみてください。

それでも、改善されない場合、教えていただきたいことがございます。
・バイナリファイルはご自身でビルドされましたか？
・dllフォルダ内にHnx8.ReadJEnc.dllが存在していますか？
よろしくお願いします。

**Comment by Mr-Ojii** [comment]
@25250512 
前回のコメントより、10日が経過したため、再びコメントいたします。
現在、そちらの状況が把握できないため、修正のしようがありません。
すで例外が発生しない状況になっているとしても、ご返信をいただけませんか？
よろしくお願いします。

**Comment by 25250512** [comment]
再ビルドして署名なしでいけました！　報告遅れて申し訳ないです

**Comment by Mr-Ojii** [comment]
よかったです～
では、このIssueはクローズいたします。
