### ISSUE TITLE
演奏速度を変更するとエラーが発生する

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#67]
演奏速度を変更するとエラーが発生します。

**Comment by Mr-Ojii** [comment]
発生したエラー内容を教えてもらえないでしょうか？

**Comment by ghost** [comment]
エラーでgithubが開かなかったためスクショを送ります。
![演奏画面で開いた場合](https://user-images.githubusercontent.com/49609325/95645444-02cca580-0afa-11eb-9d40-f677e7ffc106.png)
![特訓モードで開いた場合](https://user-images.githubusercontent.com/49609325/95645446-04966900-0afa-11eb-8b01-1bd5786b7ad9.png)

**Comment by Mr-Ojii** [comment]
ありがとうございます。

> 演奏速度を変更するとエラーが発生します。

具体的には、どのような数値にした場合にエラーが発生したのでしょうか？

**Comment by ghost** [comment]
1.0以下ですね。1.0以上は大丈夫です。

**Comment by Mr-Ojii** [comment]
ありがとうございます。
修正いたします。

**Comment by Mr-Ojii** [comment]
修正いたしました。ご確認ください。

**Comment by ghost** [comment]
治りましたが１.0にすると音源が再生されなくなりました。PlaySpeedNotEqualOneNoSoundはONにしています。

**Comment by Mr-Ojii** [comment]
それは、特訓モードで確認した数値でしょうか？
そうである場合、1.05倍になっていないか確認していただけませんか？

**Comment by ghost** [comment]
すみません確認不足でした。修正ありがとうございました
