### ISSUE TITLE
AVI動画が指定されている譜面を選択するとソフトが落ちる

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#68]
AVI動画が指定されている譜面を選択すると読み込み画面からソフトが落ちます

**Comment by Mr-Ojii** [comment]
すみません。
こちらの環境では、同様の動作が再現できませんでしたので、
動画ファイルの形式を教えていただけないでしょうか？(動画ファイルの送付でも構いません。)

**Comment by ghost** [comment]
動画形式はmp4です。 フレーム幅1280 高さ720です。

**Comment by Mr-Ojii** [comment]
コンテナ・動画コーデック・音声コーデックも教えていただけませんか？

**Comment by ghost** [comment]
コンテナはわかりません 動画コーデック・音声コーデックはこちらのサイト参考に設定しました。https://ja.osdn.net/projects/dtxmania/wiki/DirectShow%E5%AF%BE%E5%BF%9C%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by Mr-Ojii** [comment]
確かにこのソフトはDTXManiaをForkしたものから派生したソフトですが、動画デコード/音声デコード関係を作成しなおしたので、[こちらのURL](https://ja.osdn.net/projects/dtxmania/wiki/DirectShow%E5%AF%BE%E5%BF%9C%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)の操作は必要ありません。

また、私が知りたいのは、当該ファイルの動画/音声コーデックです。

**Comment by Mr-Ojii** [comment]
コーデックって何？という場合であれば、何を用いてそのファイルを作成したのかを教えていただければ、こちらでコーデックを判別できる可能性があります。
よろしくお願いします。

**Comment by ghost** [comment]
わからないので譜面を送ります。https://drive.google.com/file/d/1Fdz3cvXvsXyBejce32VODhiLRYmz0Y3f/view?usp=sharing

**Comment by Mr-Ojii** [comment]
すみません。
ありがとうございます。

**Comment by Mr-Ojii** [comment]
別件の対応していたので、遅くなってしまいました。
すみません。
私の環境では再生できますね…

![20201025224741](https://user-images.githubusercontent.com/59733587/97108972-21df5000-1714-11eb-8e97-2c2a8d6f3c42.png)

**Comment by ghost** [comment]
ダウンロードしなおしてビルドしてみたのですがやっぱり再生できず落ちます。
[2020-10-25 22-55-59.zip](https://github.com/Mr-Ojii/TJAPlayer3-f/files/5434878/2020-10-25.22-55-59.zip)

**Comment by ghost** [comment]
前のバージョン？(Commits on Oct 22, 2020)のソフトは再生できました。何か変更しましたか？

**Comment by Mr-Ojii** [comment]
変更しました。
ですが、直接的に例外につながる変更はしていないつもりです。

別環境で、再び確認いたします。
申し訳ございませんが、今しばらくお待ちください。

**Comment by Mr-Ojii** [comment]
申し訳ございません。
先ほど別環境で確認・Releaseビルドのものを開発環境で動作させたところ、同様のエラーが発生いたしました。

例外のエラーが出ないもので、発生場所を把握しにくい状況ですが、リソースの食いすぎ・メモリアクセス違反などが可能性として挙げられます。
エラーを修正し、現環境で落ちることがなくなり次第、更新いたします。

**Comment by Mr-Ojii** [comment]
エラーを修正いたしました。
いや、「私の環境ではエラーが発生しなくなりました。」と言ったほうが適切ですね。

ご確認ください。

**Comment by ghost** [comment]
問題なく再生できました。修正ありがとうございます

**Comment by Mr-Ojii** [comment]
よかったです。
では、こちらのIssueはクローズさせていただきます。
