### ISSUE TITLE
BPMが負の値であるとフリーズする

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#7]
BPMCHANGEが負の値であるとフリーズしてしまうのを修正してほしいです。
参考になれば　http://github.com/AioiLight/TJAPlayer3/pull/346/commits/019db004c7d089fb34971e39ee19d7a420cf688b

**Comment by Mr-Ojii** [comment]
BPMが負の値である時は、全く考えていませんでした。
参考になります！ありがとうございます！
コメントを追加して、先にこちらのバグを修正いたします。

**Comment by ghost** [comment]
追加です。負の値の時にランナーが逆流してしまうのでそちらも修正お願いします。
http://github.com/AioiLight/TJAPlayer3/pull/347/files

又、負の値のギミックが対応していないようです。
[Sa1 SELF CONTROL!!(full)(歌詞付).zip](https://github.com/Mr-Ojii/TJAPlayer3-f/files/4480726/Sa1.SELF.CONTROL.full.zip)
負の値に入るとと横にスライド？したり、連打が伸びるギミックなどを作ってくれると嬉しいです。詳しくは太鼓さん次郎などで見てもらえると助かります。

**Comment by Mr-Ojii** [comment]
[こちらのコミット](https://github.com/Mr-Ojii/TJAPlayer3-f/commit/c7d739c17117f1dc496eb69ed23bd48f8f2c3a10)にて、連打が伸びるギミックを実装いたしました。

**Comment by ghost** [comment]
確認してみましたが伸びていないような気がします

**Comment by Mr-Ojii** [comment]
JPOSSCROLLでジャッジの場所を動かして確認してみてもらえると、
伸びていることがわかると思います。

**Comment by ghost** [comment]
1P側は確認できました。2P側の対応も可能でしょうか？

**Comment by Mr-Ojii** [comment]
2P側にもすでに実装しているはずです。
こちらの環境だと、2P側も伸びているのですが、伸びていないでしょうか？

**Comment by ghost** [comment]
すみません。確認不足でした。
