### ISSUE TITLE
マイナススクロールの連打が正しく表示されないバグ

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#73]
#SCROLLの値がマイナスになっている状態で連打を配置すると、連打の始点と終点だけが表示されて、その間が補完されない。
→次郎のように、(ノーツを反転させて？)正常に表示させる。(しかし、ノーツの影の向きまで逆になってしまう問題もあるので、そこは考え所ではある。)

**Comment by Mr-Ojii** [comment]
Notesを反転させ、正常に表示できるように修正いたしました。
ご確認ください。

**Comment by ghost** [comment]
Notes.png部分は正常に表示されるように修正されていました。ありがとうございます。
![20210104163109](https://user-images.githubusercontent.com/66207037/103511671-d59a5400-4eaa-11eb-98bb-1622ce2d5d3a.png)
しかし、SENotes.png部分の連打の終点が反転されていませんでした。修正お願いいたします。

**Comment by Mr-Ojii** [comment]
SENotes.png部分の連打の終点も反転いたしました。
ご確認ください。

**Comment by ghost** [comment]
確認致しました。修正ありがとうございます。
加えてになりますが、上の画像で、反転された"連打ー"と"ー(伸ばし棒)"の間に縦線があるのですが、#scrollの値が正だとそれが発生しません。このバグ(？)の修正、お願いします。

**Comment by ghost** [comment]
大変遅くなりました。
修正を確認させていただきました。
ありがとうございます。
