### ISSUE TITLE
BPMがマイナスの時に歌詞が逆向きになる

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#76]
BPMがマイナスの時に歌詞が逆向きになります。
![無題](https://user-images.githubusercontent.com/76889349/103760491-87c34e80-5058-11eb-8b63-95a9d003515c.png)

**Comment by Mr-Ojii** [comment]
描画方式を変えたため、上記のバグは発生しなくなったはずです。
よって、Closeします。
