### ISSUE TITLE
エラー画面の復活

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#8]
前のバージョンではエラーが出てきますが、現在のバージョンではエラー画面が出ずアプリが落ちてしまいます。デバッグの時にしかエラーが見れないので不便です。TJAP3の開発者がうっとうしくて消したそうです。（多分）べつにうっとうしくもないし、逆に見ずらいので出きれば出るようにしてほしいです。

**Comment by Mr-Ojii** [comment]
Releaseでビルドすれば、エラーが出てくるので、
Debugでビルドしても、エラーを出すように変更します。

私もDebugビルドでソフトが落ちた時に、エラーメッセージが出ないので、
毎回Releaseでビルドするという変なことをしてたので変更します。

**Comment by Mr-Ojii** [comment]
エラー画面復活したはずです。
どうでしょうか。

**Comment by ghost** [comment]
戻りました。ありがとうございます。
