### ISSUE TITLE
曲名等をFlyingNotesより上に表示する

### ISSUE THREAD

**Issue by Hamaryo226** [Mr-Ojii/TJAPlayer3-f#81]
演奏右上の曲名,サブタイトル,ジャンルバーがFlyingNotesで
見えなくなってしまっているので見えるよう上に表示してほしいです。

**Comment by Mr-Ojii** [comment]
修正いたしました。ご確認ください。

**Comment by Hamaryo226** [comment]
確認できました！
お忙しい中ありがとうございます。🙇‍♂️
