### ISSUE TITLE
歌詞の新規表示

### ISSUE THREAD

**Issue by ghost** [Mr-Ojii/TJAPlayer3-f#9]
今の歌詞の表示はLYRIC命令を使って歌詞を表示してますが、新規でウォークマンなどに使われているlrcファイルを呼びだして歌詞を表示するようにしてほしいです。LYRIC命令だと譜面などに不具合が出るときのあるのでlrcファイルからも歌詞を表示できるようにしてほしいです。

**Comment by Mr-Ojii** [comment]
lrcファイルを読み込むコードも書かなければいけなくなるので時間はかかりますが、
頑張ります。

**Comment by Mr-Ojii** [comment]
すみません。歌詞の新規表示とは話がずれますが、
LYRIC命令で起こる不具合は具体的にはどのようなものでしょうか。
TJAP3-fの不具合でしたら、修正したいと思ったのですが。

**Comment by ghost** [comment]
lyric命令追加したりするとたまに譜面がずれたりします。

**Comment by Mr-Ojii** [comment]
承知いたしました。

**Comment by Mr-Ojii** [comment]
lrcファイル呼び出しを実装したので、よろしければどうぞ。

譜面に
LYRICFILE:hogehoge.lrc
とlrcファイル名を指定してもらえれば字幕が出るはずです。

**Comment by ghost** [comment]
readmeに+1秒ずれると書いてありましたが仕様でしょうか？

**Comment by Mr-Ojii** [comment]
仕様というより、バグです。
実装したばかりの段階なので、±1秒ほどの誤差が出てしまうかもしれないということを、
注意書きということで、一応ReadMeに書きました。(原因究明中です。)

誤解をさせてしまってすみません。

**Comment by ghost** [comment]
分かりました。ありがとうございます。

**Comment by ghost** [comment]
NEXTSONGでも設定できるようにできませんか？

**Comment by Mr-Ojii** [comment]
既存の命令にはあまり変更を加えたくないので、
lyricfile:hoge1.lrc,hoge2.lrc
のようにカンマ区切りで曲ごとに指定できるように致します。

**Comment by Mr-Ojii** [comment]
Issueの方での言及をしていませんでした。
NEXTSONGへの対応を致しましたので、ご確認ください。
詳しいことは、[追加命令について.md](https://github.com/Mr-Ojii/TJAPlayer3-f/blob/master/Test/追加命令について.md)に書いております。

**Comment by ghost** [comment]
追加命令についての通りにやりましたが一曲目のlrcファイルが読み込めません。サンプル譜面ありませんか？

**Comment by ghost** [comment]
無事にファイルの読み込みができました。ありがとうございました。

**Comment by Mr-Ojii** [comment]
それはよかったです。
lrcファイル形式には準拠していると思いますが、
読み込めないlrcファイルがあったら教えてもらえると、助かります。
では、このIssueはCloseさせていただきます。
